name: phytopipe
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - trinity=2.9.1
  - blast=2.12.0
  - diamond=0.9.21
  - bcftools=1.11
  - spades=3.13.0
  - bbmap=38.84
  - bedtools=2.30.0
  - kaiju=1.8.0
  - fastqc=0.12.1
  - krona=2.8.1
  - mummer4=4.0.0rc1
  - seqtk=1.3
  - bwa=0.7.17
  - parallel
  - pip
  - pip:
    - snakemake==7.24.0
    - biopython==1.81
    - multiqc==1.14
    - quast==5.2.0
    - pysam==0.20.0
    - scipy==1.10.1
    - pandas==1.5.3
