name: phytopipe
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - trinity=2.15.1
  - blast=2.16.0
  - diamond=2.1.11
  - bcftools=1.21
  - spades=4.1.0
  - bbmap=39.19
  - bedtools=2.31.0
  - kaiju=1.10.1
  - fastqc=0.12.1
  - krona=2.8.1
  - mummer4=4.0.0rc1
  - seqtk=1.3
  - bwa=0.7.17
  - parallel
  - pip
  - pip:
    - snakemake==7.24.0
    - biopython==1.81
    - multiqc==1.12
    - quast==5.2.0
    - pysam==0.20.0
    - scipy==1.10.1
    - pandas==1.5.3
    - pulp==2.7.0
